name: Sunny The Bus
favicon: null
layout_spectrum: 0.637461427366361
typography_spectrum: 0.33674506098032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6639987698290497
  lightness: 0.4047607076354325
  saturation: 0.040761103155091405
  rhythmicContrast: 0.8514038205612451
purpose: []
